### ISSUE TITLE
When I use pipeline module it generates models directory one in another. It needs to be fixed.  

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [Ruzzg/perlib#2]
**Describe the bug**
When I use pipeline module it generates models directory one in another. It needs to be fixed. 
By the way, thanks for such a lovely framework.
**To Reproduce**
1. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ruzgarkanar** [comment]
Thanks for pointing out that issue.Fixed
